#!/usr/bin/node
const puppeteer = require('puppeteer')
const opacity = require('../opacity')

const blackBody = "data:text/html;charset=utf-8;base64,PGJvZHkgc3R5bGU9ImJhY2tncm91bmQ6IGJsYWNrOyI+PC9ib2R5Pg=="

const URI = process.argv[2] || 'about:blank'

;(async () => {
  const args=[
    '--no-default-browser-check',
    '--no-first-run',
    '--autoplay-policy=no-user-gesture-required',
    '--kiosk',
    '--noerrdialogs',
    '--start-fullscreen',
    '--disable-infobars',
    '--disable-session-crashed-bubble',
    '--password-store=basic',
    blackBody
  ]

  opacity(0) // hide browser window as chromium flickers into existence

  const browser = await puppeteer.launch({
    timeout: 90000,
    args,
    headless: false,
    ignoreDefaultArgs: ['--mute-audio'],
    userDataDir: process.env.HOME + '/.config/chromium',
	  defaultViewport: {
      width: 1920,
      height: 1080,
      hasTouch: true
    }
  })
  const page = await browser.newPage();
  await page.goto(URI, {
    timeout: 90000
  })
  setTimeout( ()=> opacity(100), 1000)
})();
